export default [
    {
        author: 'Elon Musk',
        handle: 'elonmusk',
        time: '23h',
        body: 'Amazing show about <a href="#"> @Inspiration4x</a> mission!',
        image: 'countdown.jpg',
        image_title: 'Countdown: Inspiration4 Mission to Space | Netflix Official Site',
        image_body: 'From training to launch to landing, this all-access docuseries rides along with the Inspiration4 crew on the first all-civilian orbital space ...',
        image_link: 'netflix.com',
        author_image: 'rocket.jpg',
        comments: '4.2K',
        retweets: '3.5K',
        likes: '37.5K',
        embed: true,
    },
    {
        author: 'New York Post',
        handle: 'nypost',
        time: '23h',
        body: 'Grimes seen reading Karl Marx following split with world\'s richest man Elon Musk <a href="#">trib.al/nx2Gfaq</a>',
        image: 'grimes.jpg',
        author_image: 'nyp.png',
        comments: '965',
        retweets: '2.4K',
        likes: '4K',
        embed: false,
    },];
